apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: eg
    meta.helm.sh/release-namespace: envoy-gateway-system
  labels:
    app.kubernetes.io/instance: eg
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/version: v1.3.2
    control-plane: envoy-gateway
    helm.sh/chart: gateway-helm-v1.3.2
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: eg
    app.kubernetes.io/name: gateway-helm
    control-plane: envoy-gateway
  ports:
  - name: grpc
    nodePort: 31197
    port: 18000
    protocol: TCP
    targetPort: 18000
  - name: ratelimit
    nodePort: 30983
    port: 18001
    protocol: TCP
    targetPort: 18001
  - name: wasm
    nodePort: 30317
    port: 18002
    protocol: TCP
    targetPort: 18002
  - name: metrics
    nodePort: 31820
    port: 19001
    protocol: TCP
    targetPort: 19001
  - name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 18000
  - name: https
    nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: 18001