apiVersion: v1
kind: Service
metadata:
  name: fake-shop
  namespace: fake-shop
spec:
  type: LoadBalancer
  selector:
    app: fake-shop
  ports:
  - port: 80 # recebe na porta 80 e redireciona para a porta 5000 do container
    targetPort: 5000